name: Deploy

on:
  push:
    branches: [main]
  # pull_request:
  #   branches: [ main ]

jobs:
  build:
    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [16.x]

    steps:
      - uses: actions/checkout@v2

      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v1
        with:
          node-version: ${{ matrix.node-version }}

      - name: Build
        run: |
          yarn
          yarn add -D webpack-cli
          yarn build:export

      - name: FTP
        uses: SamKirkland/FTP-Deploy-Action@4.3.0
        with:
          server: ${{ secrets.INFINITY_FREE_HOST }}
          username: ${{ secrets.INFINITY_FREE_FTP_USER_NAME }}
          password: ${{ secrets.INFINITY_FREE_FTP_PW }}
          protocol: ftps
          local-dir: ./out/
          server-dir: ./htdocs/
